name: Build

on:
  push:
    branches:
      - master
      - ci-test
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-VERSION: ${{ matrix.go }}
      - uses: actions/cache@v2
        id: gomod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go vet
      - name: Run unit tests
        run: go test -tags unit -race
  integration-yugabyte:
    timeout-minutes: 10
    needs:
      - build
    name: Integration Tests (Yugabyte)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/cache@v2
        id: gomod-cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup YugabyteDB cluster
        uses: jameshartig/yugabyte-db-action@master
        id: yb
      - name: Integration tests
        run: |
          go test -tags "yugabyte cassandra gocql_debug" -timeout=5m -race ./...
